fem: cie::fem::maths::Polynomial< TValue > Class Template Reference
cie::fem::maths::Polynomial< TValue > Class Template Reference
Expression representing a scalar polynomial.
Public Types
using Derivative = Polynomial
using Coefficients = DynamicArray< TValue >
Public Types inherited from cie::fem::maths::ExpressionTraits< TValue >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Public Member Functions
Polynomial () noexcept=default
Uninitialized by default.
Polynomial (RightRef< Coefficients > r_coefficients) noexcept
Construct from a container of coefficients.
template<concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
Polynomial (TItBegin it_begin, TItEnd it_end)
Construct from a range of coefficients.
Polynomial (Polynomial &&r_rhs) noexcept=default
Polynomial (Ref< const Polynomial > r_rhs)=default
Ref< Polynomial > operator= (RightRef< Polynomial > r_rhs) noexcept=default
Ref< Polynomial > operator= (Ref< const Polynomial > r_rhs)=default
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_resultBegin) const
unsigned size () const noexcept
Get the number of scalar components returned by evaluate.
Polynomial makeDerivative () const
Construct the derivative of the Polynomial.
Protected Attributes
Coefficients _coefficients
Detailed Description
template<class TValue>
class cie::fem::maths::Polynomial< TValue >
Expression representing a scalar polynomial.
Member Typedef Documentation
Coefficients
template<class TValue > using cie::fem::maths::Polynomial< TValue >::Coefficients = DynamicArray<TValue>
Derivative
template<class TValue > using cie::fem::maths::Polynomial< TValue >::Derivative = Polynomial
Constructor & Destructor Documentation
Polynomial() [1/5]
template<class TValue > cie::fem::maths::Polynomial< TValue >::Polynomial () default noexcept
Uninitialized by default.
Polynomial() [2/5]
template<class TValue > cie::fem::maths::Polynomial< TValue >::Polynomial (RightRef< Coefficients > r_coefficients) noexcept
Construct from a container of coefficients.
The input coefficients are expected to be sorted in the order of their corresponding monomials.
Polynomial() [3/5]
template<class TValue > template<concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd> cie::fem::maths::Polynomial< TValue >::Polynomial (TItBegin it_begin, TItEnd it_end)
Construct from a range of coefficients.
The input coefficients are expected to be sorted in the order of their corresponding monomials.
Polynomial() [4/5]
template<class TValue > cie::fem::maths::Polynomial< TValue >::Polynomial (Polynomial< TValue > && r_rhs) default noexcept
Polynomial() [5/5]
template<class TValue > cie::fem::maths::Polynomial< TValue >::Polynomial (Ref< const Polynomial< TValue > > r_rhs) default
Member Function Documentation
evaluate()
template<class TValue > void cie::fem::maths::Polynomial< TValue >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_resultBegin) const
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
makeDerivative()
template<class TValue > Polynomial cie::fem::maths::Polynomial< TValue >::makeDerivative () const
Construct the derivative of the Polynomial.
The returned object is also a Polynomial, irrespective of the current polynomial order.
operator=() [1/2]
template<class TValue > Ref<Polynomial> cie::fem::maths::Polynomial< TValue >::operator= (Ref< const Polynomial< TValue > > r_rhs) default
operator=() [2/2]
template<class TValue > Ref<Polynomial> cie::fem::maths::Polynomial< TValue >::operator= (RightRef< Polynomial< TValue > > r_rhs) default noexcept
size()
template<class TValue > unsigned cie::fem::maths::Polynomial< TValue >::size () const noexcept
Get the number of scalar components returned by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Member Data Documentation
_coefficients
template<class TValue > Coefficients cie::fem::maths::Polynomial< TValue >::_coefficients protected
The documentation for this class was generated from the following file:
Polynomial.hpp