fem: cie::fem::maths::LambdaExpression< TLambda, TValue > Class Template Reference
cie::fem::maths::LambdaExpression< TLambda, TValue > Class Template Reference
Public Member Functions
LambdaExpression (RightRef< TLambda > r_lambda, unsigned size) noexcept
LambdaExpression (Ref< const TLambda > r_lambda, unsigned size)
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
unsigned size () const noexcept
Additional Inherited Members
Public Types inherited from cie::fem::maths::ExpressionTraits< TValue >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Constructor & Destructor Documentation
LambdaExpression() [1/2]
template<class TLambda , concepts::Numeric TValue> cie::fem::maths::LambdaExpression< TLambda, TValue >::LambdaExpression (RightRef< TLambda > r_lambda, unsigned size) inline noexcept
LambdaExpression() [2/2]
template<class TLambda , concepts::Numeric TValue> cie::fem::maths::LambdaExpression< TLambda, TValue >::LambdaExpression (Ref< const TLambda > r_lambda, unsigned size) inline
Member Function Documentation
evaluate()
template<class TLambda , concepts::Numeric TValue> void cie::fem::maths::LambdaExpression< TLambda, TValue >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const inline
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
size()
template<class TLambda , concepts::Numeric TValue> unsigned cie::fem::maths::LambdaExpression< TLambda, TValue >::size () const inline noexcept
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
The documentation for this class was generated from the following file:
LambdaExpression.hpp