fem: cie::fem::AttributeContainer< TValues > Class Template Reference
cie::fem::AttributeContainer< TValues > Class Template Reference
Public Types
using Values = std::tuple< TValues... >
Public Member Functions
AttributeContainer () noexcept=default
AttributeContainer (Size size)
void resize (Size size)
void erase (Size i_begin, Size i_end)
void erase (Size index)
void clear ()
void reserve (Size capacity)
void push_back (TValues... values)
Size size () const noexcept
Size capacity () const noexcept
bool empty () const noexcept
std::tuple< TValues... > get (Size index) const noexcept
template<class TValue >
TValue at (Size index) const noexcept
template<class TValue >
Ref< TValue > at (Size index) noexcept
template<class ... TArguments, class TVisitor >
auto visit (Size index, TVisitor &&r_visitor) const
template<class TValue >
DynamicArray< TValue >::const_iterator begin () const noexcept
template<class TValue >
DynamicArray< TValue >::iterator begin () noexcept
template<class TValue >
DynamicArray< TValue >::const_iterator end () const noexcept
template<class TValue >
DynamicArray< TValue >::iterator end () noexcept
Member Typedef Documentation
Values
template<class ... TValues> using cie::fem::AttributeContainer< TValues >::Values = std::tuple<TValues...>
Constructor & Destructor Documentation
AttributeContainer() [1/2]
template<class ... TValues> cie::fem::AttributeContainer< TValues >::AttributeContainer () default noexcept
AttributeContainer() [2/2]
template<class ... TValues> cie::fem::AttributeContainer< TValues >::AttributeContainer (Size size)
Member Function Documentation
at() [1/2]
template<class ... TValues> template<class TValue > TValue cie::fem::AttributeContainer< TValues >::at (Size index) const noexcept
at() [2/2]
template<class ... TValues> template<class TValue > Ref<TValue> cie::fem::AttributeContainer< TValues >::at (Size index) noexcept
begin() [1/2]
template<class ... TValues> template<class TValue > DynamicArray<TValue>::const_iterator cie::fem::AttributeContainer< TValues >::begin () const noexcept
begin() [2/2]
template<class ... TValues> template<class TValue > DynamicArray<TValue>::iterator cie::fem::AttributeContainer< TValues >::begin () noexcept
capacity()
template<class ... TValues> Size cie::fem::AttributeContainer< TValues >::capacity () const noexcept
Referenced by fem.discretization.element.LinearHeatElement1D::copy(), fem.discretization.element.NonlinearHeatElement1D::copy(), fem.discretization.element.LinearHeatElement1D::integrateMass(), fem.discretization.element.NonlinearHeatElement1D::integrateMass(), and fem.optcontrol.adjointelement.AdjointHeatElement1D::integrateMass().
clear()
template<class ... TValues> void cie::fem::AttributeContainer< TValues >::clear ()
empty()
template<class ... TValues> bool cie::fem::AttributeContainer< TValues >::empty () const noexcept
end() [1/2]
template<class ... TValues> template<class TValue > DynamicArray<TValue>::const_iterator cie::fem::AttributeContainer< TValues >::end () const noexcept
end() [2/2]
template<class ... TValues> template<class TValue > DynamicArray<TValue>::iterator cie::fem::AttributeContainer< TValues >::end () noexcept
erase() [1/2]
template<class ... TValues> void cie::fem::AttributeContainer< TValues >::erase (Size i_begin, Size i_end)
erase() [2/2]
template<class ... TValues> void cie::fem::AttributeContainer< TValues >::erase (Size index)
get()
template<class ... TValues> std::tuple<TValues...> cie::fem::AttributeContainer< TValues >::get (Size index) const noexcept
push_back()
template<class ... TValues> void cie::fem::AttributeContainer< TValues >::push_back (TValues... values)
reserve()
template<class ... TValues> void cie::fem::AttributeContainer< TValues >::reserve (Size capacity)
resize()
template<class ... TValues> void cie::fem::AttributeContainer< TValues >::resize (Size size)
size()
template<class ... TValues> Size cie::fem::AttributeContainer< TValues >::size () const noexcept
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
visit()
template<class ... TValues> template<class ... TArguments, class TVisitor > auto cie::fem::AttributeContainer< TValues >::visit (Size index, TVisitor && r_visitor) const inline
The documentation for this class was generated from the following file:
AttributeContainer.hpp