fem: cie::fem::Quadrature< TValue, Dimension > Class Template Reference
cie::fem::Quadrature< TValue, Dimension > Class Template Reference
Public Member Functions
Quadrature (Ref< const QuadratureBase< TValue >> r_base)
Quadrature (Ref< const typename QuadratureBase< TValue >::NodeContainer > r_nodes, Ref< const typename QuadratureBase< TValue >::WeightContainer > r_weights)
template<maths::Expression TExpression>
void evaluate (Ref< const TExpression > r_expression, typename TExpression::Iterator it_bufferBegin, typename TExpression::Iterator it_out) const
template<maths::Expression TExpression>
void evaluate (Ref< const TExpression > r_expression, typename TExpression::Iterator it_outBegin) const
template<class TOutputIt >
void getIntegrationPoints (TOutputIt it_output) const
template<class TOutputIt >
void getIntegrationWeights (TOutputIt it_output) const
Additional Inherited Members
Public Types inherited from cie::fem::Kernel< Dimension, TValue >
using Value = NT
using number_type = NT
using dynamic_array = linalg::EigenMatrix< Eigen::Matrix< NT, Eigen::Dynamic, 1 > >
using static_array = linalg::StaticEigenMatrix< NT, ArraySize, 1 >
using Point = detail::Point< Dimension, NT >
using LocalPoint = detail::LocalPoint< Dimension, NT >
using GlobalPoint = detail::GlobalPoint< Dimension, NT >
Static Public Attributes inherited from cie::fem::Kernel< Dimension, TValue >
static const Size dimension
Constructor & Destructor Documentation
Quadrature() [1/2]
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::Quadrature< TValue, Dimension >::Quadrature (Ref< const QuadratureBase< TValue >> r_base)
Quadrature() [2/2]
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::Quadrature< TValue, Dimension >::Quadrature (Ref< const typename QuadratureBase< TValue >::NodeContainer > r_nodes, Ref< const typename QuadratureBase< TValue >::WeightContainer > r_weights)
Member Function Documentation
evaluate() [1/2]
template<concepts::Numeric TValue, unsigned Dimension> template<maths::Expression TExpression> void cie::fem::Quadrature< TValue, Dimension >::evaluate (Ref< const TExpression > r_expression, typename TExpression::Iterator it_bufferBegin, typename TExpression::Iterator it_out) const
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
evaluate() [2/2]
template<concepts::Numeric TValue, unsigned Dimension> template<maths::Expression TExpression> void cie::fem::Quadrature< TValue, Dimension >::evaluate (Ref< const TExpression > r_expression, typename TExpression::Iterator it_outBegin) const
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
getIntegrationPoints()
template<concepts::Numeric TValue, unsigned Dimension> template<class TOutputIt > void cie::fem::Quadrature< TValue, Dimension >::getIntegrationPoints (TOutputIt it_output) const
getIntegrationWeights()
template<concepts::Numeric TValue, unsigned Dimension> template<class TOutputIt > void cie::fem::Quadrature< TValue, Dimension >::getIntegrationWeights (TOutputIt it_output) const
The documentation for this class was generated from the following file:
Quadrature.hpp