fem: cie::fem::maths::AffineTransform< TValue, Dimension > Class Template Reference
cie::fem::maths::AffineTransform< TValue, Dimension > Class Template Reference
Fem
Class representing an affine transformation.
Public Types
using TransformationMatrix = typename Kernel< Dimension, TValue >::dense::template static_matrix< Dimension+1, Dimension+1 >
Public Member Functions
AffineTransform () noexcept
Identity transform by default.
template<concepts::Iterator TPointIt>
AffineTransform (TPointIt it_transformedBegin, TPointIt it_transformedEnd)
Affine transformation from (D+1) transformed points.
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
unsigned size () const noexcept
Get the number of scalar components returned by evaluate.
AffineTransformDerivative< TValue, Dimension > makeDerivative () const noexcept
Construct the derivative of the affine transform.
AffineTransform makeInverse () const
Construct the inverse transform.
Ref< const TransformationMatrix > getTransformationMatrix () const noexcept
Get the matrix representation of the transformation.
Detailed Description
template<concepts::Numeric TValue, unsigned Dimension>
class cie::fem::maths::AffineTransform< TValue, Dimension >
Class representing an affine transformation.
Uniquely defines a mapping between any pair of triangles in the specified dimension.
Member Typedef Documentation
TransformationMatrix
template<concepts::Numeric TValue, unsigned Dimension> using cie::fem::maths::AffineTransform< TValue, Dimension >::TransformationMatrix = typename Kernel<Dimension,TValue>::dense::template static_matrix<Dimension+1, Dimension+1>
Constructor & Destructor Documentation
AffineTransform() [1/2]
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::AffineTransform< TValue, Dimension >::AffineTransform () noexcept
Identity transform by default.
AffineTransform() [2/2]
template<concepts::Numeric TValue, unsigned Dimension> template<concepts::Iterator TPointIt> cie::fem::maths::AffineTransform< TValue, Dimension >::AffineTransform (TPointIt it_transformedBegin, TPointIt it_transformedEnd)
Affine transformation from (D+1) transformed points.
The transformation is characterized by how it deforms a cube defined on \([-1,1]^D \). Not all corners of the deformed cube are necessary, but only the base \([-1]^D \) and its adjecent ones (\(D+1 \) points in total). For example, the transformed location of the following vertices are required in 2D:
\[ \begin{bmatrix} -1 & 1 & -1 \\ -1 & -1 & 1 \end{bmatrix} \]
To avoid unintended overlapping transformations, the order of vertices should match the following pattern (example in 3D):
\[ \begin{bmatrix} -1 & 1 & -1 & -1 \\ -1 & -1 & 1 & -1 \\ -1 & -1 & -1 & 1 \end{bmatrix} \]
Parameters
it_transformedBegin iterator pointing to the transformed cube's base \([-1]^D \).
it_transformedEnd iterator past the last transformed point (should be identical to it_transformedBegin + D + 1 + 1).
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::AffineTransform< TValue, Dimension >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
getTransformationMatrix()
template<concepts::Numeric TValue, unsigned Dimension> Ref<const TransformationMatrix> cie::fem::maths::AffineTransform< TValue, Dimension >::getTransformationMatrix () const noexcept
Get the matrix representation of the transformation.
makeDerivative()
template<concepts::Numeric TValue, unsigned Dimension> AffineTransformDerivative<TValue,Dimension> cie::fem::maths::AffineTransform< TValue, Dimension >::makeDerivative () const noexcept
Construct the derivative of the affine transform.
makeInverse()
template<concepts::Numeric TValue, unsigned Dimension> AffineTransform cie::fem::maths::AffineTransform< TValue, Dimension >::makeInverse () const
Construct the inverse transform.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::AffineTransform< TValue, Dimension >::size () const noexcept
Get the number of scalar components returned by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
The documentation for this class was generated from the following file:
AffineTransform.hpp