fem: cie::fem::maths::ScaleTranslateTransform< TValue, Dimension > Class Template Reference
cie::fem::maths::ScaleTranslateTransform< TValue, Dimension > Class Template Reference
Fem
Class representing independent scaling along orthogonal coordinate axes, followed by a translation.
Public Member Functions
ScaleTranslateTransform () noexcept
Identity transform by default.
template<concepts::Iterator TPointIt>
ScaleTranslateTransform (TPointIt it_transformedBegin, TPointIt it_transformedEnd)
Construct from the transformed base and the vertex opposite \([1]^D \).
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
unsigned size () const noexcept
Get the number of components written by evaluate.
ScaleTranslateTransformDerivative< TValue, Dimension > makeDerivative () const noexcept
Construct the derivative of the transform.
TranslateScaleTransform< TValue, Dimension > makeInverse () const noexcept
Construct the inverse of the transform.
Friends
class ScaleTranslateTransformDerivative< TValue, Dimension >
class TranslateScaleTransform< TValue, Dimension >
Detailed Description
template<concepts::Numeric TValue, unsigned Dimension>
class cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >
Class representing independent scaling along orthogonal coordinate axes, followed by a translation.
Uniquely defines a mapping between axis-aligned hyperrectangles in D-dimensional space.
Constructor & Destructor Documentation
ScaleTranslateTransform() [1/2]
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >::ScaleTranslateTransform () noexcept
Identity transform by default.
ScaleTranslateTransform() [2/2]
template<concepts::Numeric TValue, unsigned Dimension> template<concepts::Iterator TPointIt> cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >::ScaleTranslateTransform (TPointIt it_transformedBegin, TPointIt it_transformedEnd)
Construct from the transformed base and the vertex opposite \([1]^D \).
The coordinates of the input transformed vertex are identical to the scaling coefficients of the transform, after undoing the translation.
Note
The number of input components must match the dimension.
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
makeDerivative()
template<concepts::Numeric TValue, unsigned Dimension> ScaleTranslateTransformDerivative<TValue,Dimension> cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >::makeDerivative () const noexcept
Construct the derivative of the transform.
makeInverse()
template<concepts::Numeric TValue, unsigned Dimension> TranslateScaleTransform<TValue,Dimension> cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >::makeInverse () const noexcept
Construct the inverse of the transform.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::ScaleTranslateTransform< TValue, Dimension >::size () const noexcept
Get the number of components written by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Friends And Related Function Documentation
ScaleTranslateTransformDerivative< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class ScaleTranslateTransformDerivative< TValue, Dimension > friend
TranslateScaleTransform< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class TranslateScaleTransform< TValue, Dimension > friend
The documentation for this class was generated from the following file:
ScaleTranslateTransform.hpp