fem: cie::fem::maths::AffineTransformDerivative< TValue, Dimension > Class Template Reference
cie::fem::maths::AffineTransformDerivative< TValue, Dimension > Class Template Reference
Fem
Expression representing the derivative of AffineTransform.
Public Member Functions
AffineTransformDerivative () noexcept
Identity by default.
void evaluate (ConstIterator it_begin, ConstIterator it_end, Iterator it_out) const
This function is constant so the arguments are not necessary.
unsigned size () const noexcept
Get the number of scalar components returned by evaluate.
TValue evaluateDeterminant (ConstIterator it_begin, ConstIterator it_end) const
Compute the determinant of the affine transform's jacobian.
Friends
class AffineTransform< TValue, Dimension >
Additional Inherited Members
Public Types inherited from cie::fem::maths::ExpressionTraits< TValue >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Detailed Description
template<concepts::Numeric TValue, unsigned Dimension>
class cie::fem::maths::AffineTransformDerivative< TValue, Dimension >
Expression representing the derivative of AffineTransform.
Constructor & Destructor Documentation
AffineTransformDerivative()
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::AffineTransformDerivative< TValue, Dimension >::AffineTransformDerivative () noexcept
Identity by default.
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::AffineTransformDerivative< TValue, Dimension >::evaluate (ConstIterator it_begin, ConstIterator it_end, Iterator it_out) const
This function is constant so the arguments are not necessary.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
evaluateDeterminant()
template<concepts::Numeric TValue, unsigned Dimension> TValue cie::fem::maths::AffineTransformDerivative< TValue, Dimension >::evaluateDeterminant (ConstIterator it_begin, ConstIterator it_end) const
Compute the determinant of the affine transform's jacobian.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::AffineTransformDerivative< TValue, Dimension >::size () const noexcept
Get the number of scalar components returned by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Friends And Related Function Documentation
AffineTransform< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class AffineTransform< TValue, Dimension > friend
The documentation for this class was generated from the following file:
AffineTransform.hpp