fem: cie::fem::maths::AnsatzSpace< TScalarExpression, Dim > Class Template Reference
cie::fem::maths::AnsatzSpace< TScalarExpression, Dim > Class Template Reference
A set of multidimensional functions constructed from the cartesian product of a set of scalar basis functions.
Public Types
using AnsatzSet = DynamicArray< TScalarExpression >
using Derivative = AnsatzSpaceDerivative< TScalarExpression, Dim >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Public Types inherited from cie::fem::maths::ExpressionTraits< TScalarExpression::Value >
using Value = TScalarExpression::Value
using Iterator = Ptr< TScalarExpression::Value >
using ConstIterator = Ptr< const TScalarExpression::Value >
Public Member Functions
AnsatzSpace () noexcept
AnsatzSpace (AnsatzSet &&r_set) noexcept
AnsatzSpace (const AnsatzSet &r_set)
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Derivative makeDerivative () const
unsigned size () const noexcept
Static Public Attributes
static constexpr unsigned Dimension = Dim
Friends
class AnsatzSpaceDerivative< TScalarExpression, Dim >
Detailed Description
template<class TScalarExpression, unsigned Dim>
class cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >
A set of multidimensional functions constructed from the cartesian product of a set of scalar basis functions.
Member Typedef Documentation
AnsatzSet
template<class TScalarExpression , unsigned Dim> using cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::AnsatzSet = DynamicArray<TScalarExpression>
ConstIterator
template<class TScalarExpression , unsigned Dim> using cie::fem::maths::ExpressionTraits< TValue >::ConstIterator = Ptr<const TValue>
Derivative
template<class TScalarExpression , unsigned Dim> using cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::Derivative = AnsatzSpaceDerivative<TScalarExpression,Dim>
Iterator
template<class TScalarExpression , unsigned Dim> using cie::fem::maths::ExpressionTraits< TValue >::Iterator = Ptr<TValue>
Value
template<class TScalarExpression , unsigned Dim> using cie::fem::maths::ExpressionTraits< TValue >::Value = TValue
Constructor & Destructor Documentation
AnsatzSpace() [1/3]
template<class TScalarExpression , unsigned Dim> cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::AnsatzSpace () noexcept
AnsatzSpace() [2/3]
template<class TScalarExpression , unsigned Dim> cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::AnsatzSpace (AnsatzSet && r_set) noexcept
AnsatzSpace() [3/3]
template<class TScalarExpression , unsigned Dim> cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::AnsatzSpace (const AnsatzSet & r_set)
Member Function Documentation
evaluate()
template<class TScalarExpression , unsigned Dim> void cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
makeDerivative()
template<class TScalarExpression , unsigned Dim> Derivative cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::makeDerivative () const
size()
template<class TScalarExpression , unsigned Dim> unsigned cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::size () const noexcept
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Friends And Related Function Documentation
AnsatzSpaceDerivative< TScalarExpression, Dim >
template<class TScalarExpression , unsigned Dim> friend class AnsatzSpaceDerivative< TScalarExpression, Dim > friend
Member Data Documentation
Dimension
template<class TScalarExpression , unsigned Dim> constexpr unsigned cie::fem::maths::AnsatzSpace< TScalarExpression, Dim >::Dimension = Dim static constexpr
The documentation for this class was generated from the following file:
AnsatzSpace.hpp