fem: cie::fem::maths::ScaleTranslateTransformDerivative< TValue, Dimension > Class Template Reference
cie::fem::maths::ScaleTranslateTransformDerivative< TValue, Dimension > Class Template Reference
Fem
Public Member Functions
ScaleTranslateTransformDerivative () noexcept
Identity by default.
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const noexcept
Evaluate the derivative at the provided point.
TValue evaluateDeterminant (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd) const noexcept
Evaluate the determinant of the original transform's jacobian at the provided location.
unsigned size () const noexcept
Get the number of components written by evaluate.
Friends
class ScaleTranslateTransform< TValue, Dimension >
class TranslateScaleTransform< TValue, Dimension >
Additional Inherited Members
Public Types inherited from cie::fem::maths::ExpressionTraits< TValue >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Constructor & Destructor Documentation
ScaleTranslateTransformDerivative()
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::ScaleTranslateTransformDerivative< TValue, Dimension >::ScaleTranslateTransformDerivative () noexcept
Identity by default.
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::ScaleTranslateTransformDerivative< TValue, Dimension >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const noexcept
Evaluate the derivative at the provided point.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
evaluateDeterminant()
template<concepts::Numeric TValue, unsigned Dimension> TValue cie::fem::maths::ScaleTranslateTransformDerivative< TValue, Dimension >::evaluateDeterminant (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd) const noexcept
Evaluate the determinant of the original transform's jacobian at the provided location.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::ScaleTranslateTransformDerivative< TValue, Dimension >::size () const noexcept
Get the number of components written by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Friends And Related Function Documentation
ScaleTranslateTransform< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class ScaleTranslateTransform< TValue, Dimension > friend
TranslateScaleTransform< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class TranslateScaleTransform< TValue, Dimension > friend
The documentation for this class was generated from the following file:
ScaleTranslateTransform.hpp