fem: cie::fem::maths::IdentityTransform< TValue, Dimension > Class Template Reference
cie::fem::maths::IdentityTransform< TValue, Dimension > Class Template Reference
Public Types
using Derivative = IdentityTransform
Public Types inherited from cie::fem::maths::ExpressionTraits< TValue >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Public Member Functions
IdentityTransform () noexcept=default
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const noexcept
constexpr unsigned size () const noexcept
constexpr IdentityTransform makeInverse () const noexcept
constexpr Derivative makeDerivative () const noexcept
Member Typedef Documentation
Derivative
template<concepts::Numeric TValue, unsigned Dimension> using cie::fem::maths::IdentityTransform< TValue, Dimension >::Derivative = IdentityTransform
Constructor & Destructor Documentation
IdentityTransform()
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::IdentityTransform< TValue, Dimension >::IdentityTransform () default noexcept
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::IdentityTransform< TValue, Dimension >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const inline noexcept
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
makeDerivative()
template<concepts::Numeric TValue, unsigned Dimension> constexpr Derivative cie::fem::maths::IdentityTransform< TValue, Dimension >::makeDerivative () const inline constexpr noexcept
makeInverse()
template<concepts::Numeric TValue, unsigned Dimension> constexpr IdentityTransform cie::fem::maths::IdentityTransform< TValue, Dimension >::makeInverse () const inline constexpr noexcept
size()
template<concepts::Numeric TValue, unsigned Dimension> constexpr unsigned cie::fem::maths::IdentityTransform< TValue, Dimension >::size () const inline constexpr noexcept
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
The documentation for this class was generated from the following file:
IndentityTransform.hpp