fem: cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension > Class Template Reference
cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension > Class Template Reference
Fem
Class representing independent scaling along orthogonal coordinate axes.
Public Member Functions
OrthogonalScaleTransform () noexcept
Identity transform by default.
template<concepts::Iterator TPointIt>
OrthogonalScaleTransform (TPointIt it_transformedBegin, TPointIt it_transformedEnd)
Construct from the transformed vertex opposite the base \([1]^D \).
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
unsigned size () const noexcept
Get the number of components written by evaluate.
OrthogonalScaleTransformDerivative< TValue, Dimension > makeDerivative () const noexcept
Construct the derivative of the transform.
OrthogonalScaleTransform makeInverse () const
Construct the inverse transform.
Friends
class OrthogonalScaleTransformDerivative< TValue, Dimension >
Detailed Description
template<concepts::Numeric TValue, unsigned Dimension>
class cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >
Class representing independent scaling along orthogonal coordinate axes.
Uniquely defines a mapping between axis-aligned hyperrectangles in D-dimensional space, that have their base vertices at the origin.
Constructor & Destructor Documentation
OrthogonalScaleTransform() [1/2]
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >::OrthogonalScaleTransform () noexcept
Identity transform by default.
OrthogonalScaleTransform() [2/2]
template<concepts::Numeric TValue, unsigned Dimension> template<concepts::Iterator TPointIt> cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >::OrthogonalScaleTransform (TPointIt it_transformedBegin, TPointIt it_transformedEnd)
Construct from the transformed vertex opposite the base \([1]^D \).
The coordinates of the input transformed vertex are identical to the scaling coefficients of the transform.
Note
The number of input components must match the dimension.
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
makeDerivative()
template<concepts::Numeric TValue, unsigned Dimension> OrthogonalScaleTransformDerivative<TValue,Dimension> cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >::makeDerivative () const noexcept
Construct the derivative of the transform.
makeInverse()
template<concepts::Numeric TValue, unsigned Dimension> OrthogonalScaleTransform cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >::makeInverse () const
Construct the inverse transform.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::OrthogonalScaleTransform< TValue, Dimension >::size () const noexcept
Get the number of components written by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Friends And Related Function Documentation
OrthogonalScaleTransformDerivative< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class OrthogonalScaleTransformDerivative< TValue, Dimension > friend
The documentation for this class was generated from the following file:
OrthogonalScaleTransform.hpp