fem: cie::fem::maths::ProjectiveTransform< TValue, Dimension > Class Template Reference
cie::fem::maths::ProjectiveTransform< TValue, Dimension > Class Template Reference
Fem
Class representing a projective transform.
Public Types
using TransformationMatrix = typename Kernel< Dimension, TValue >::dense::template static_matrix< Dimension+1, Dimension+1 >
Public Member Functions
ProjectiveTransform () noexcept
Identity transform by default.
template<concepts::Iterator PointIt>
ProjectiveTransform (PointIt it_transformedBegin, PointIt it_transformedEnd)
Projective transformation from \(2 \cdot D \) transformed points.
void evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
unsigned size () const noexcept
Get the number of scalar components returned by evaluate.
ProjectiveTransform makeInverse () const
Construct the inverse transform.
ProjectiveTransformDerivative< TValue, Dimension > makeDerivative () const
Construct the derivative of the projective transform.
Ref< const TransformationMatrix > getTransformationMatrix () const noexcept
Get the matrix representation of the transformation.
Detailed Description
template<concepts::Numeric TValue, unsigned Dimension>
class cie::fem::maths::ProjectiveTransform< TValue, Dimension >
Class representing a projective transform.
Uniquely defines a mapping between any pair of generalized quads.
Note
Unfortunately, I haven't found the proper term for quadrilaterals generalized to arbitrary dimensions, so generalized quad will have to do for now.
Member Typedef Documentation
TransformationMatrix
template<concepts::Numeric TValue, unsigned Dimension> using cie::fem::maths::ProjectiveTransform< TValue, Dimension >::TransformationMatrix = typename Kernel<Dimension,TValue>::dense::template static_matrix<Dimension+1, Dimension+1>
Constructor & Destructor Documentation
ProjectiveTransform() [1/2]
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::ProjectiveTransform< TValue, Dimension >::ProjectiveTransform () noexcept
Identity transform by default.
ProjectiveTransform() [2/2]
template<concepts::Numeric TValue, unsigned Dimension> template<concepts::Iterator PointIt> cie::fem::maths::ProjectiveTransform< TValue, Dimension >::ProjectiveTransform (PointIt it_transformedBegin, PointIt it_transformedEnd)
Projective transformation from \(2 \cdot D \) transformed points.
The transformation is characterized by how it deforms a cube defined on \([-1,1]^D \).
To avoid unintended overlapping transformations, the order of vertices should match an outer product with smaller spatial indices varying more frequently. Example in 3D:
\[ \begin{bmatrix} -1 & 1 & -1 & 1 & -1 & 1 & -1 & 1 \\ -1 & -1 & 1 & 1 & -1 & -1 & 1 & 1 \\ -1 & -1 & -1 & -1 & 1 & 1 & 1 & 1 \end{bmatrix} \]
Parameters
it_transformedBegin iterator pointing to the transformed cube's base \([-1]^D \).
it_transformedEnd iterator past the last transformed point (should be identical to it_transformedBegin + 2 * D + 1).
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::ProjectiveTransform< TValue, Dimension >::evaluate (ConstIterator it_argumentBegin, ConstIterator it_argumentEnd, Iterator it_out) const
Apply the transformation on a vector defined by the provided components.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
getTransformationMatrix()
template<concepts::Numeric TValue, unsigned Dimension> Ref<const TransformationMatrix> cie::fem::maths::ProjectiveTransform< TValue, Dimension >::getTransformationMatrix () const noexcept
Get the matrix representation of the transformation.
makeDerivative()
template<concepts::Numeric TValue, unsigned Dimension> ProjectiveTransformDerivative<TValue,Dimension> cie::fem::maths::ProjectiveTransform< TValue, Dimension >::makeDerivative () const
Construct the derivative of the projective transform.
makeInverse()
template<concepts::Numeric TValue, unsigned Dimension> ProjectiveTransform cie::fem::maths::ProjectiveTransform< TValue, Dimension >::makeInverse () const
Construct the inverse transform.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::ProjectiveTransform< TValue, Dimension >::size () const noexcept
Get the number of scalar components returned by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
The documentation for this class was generated from the following file:
ProjectiveTransform.hpp