fem: cie::fem::AssemblyMap Class Reference
cie::fem::AssemblyMap Class Reference
Fem
Public Types
using Index = Size
using Key = StaticArray< Index, 2 >
using iterator = Map::iterator
using const_iterator = Map::const_iterator
using value_type = Map::value_type
Public Member Functions
AssemblyMap ()=default
AssemblyMap (AssemblyMap &&r_rhs)=default
AssemblyMap (const AssemblyMap &r_rhs)=default
AssemblyMap & operator= (AssemblyMap &&r_rhs)=default
AssemblyMap & operator= (const AssemblyMap &r_rhs)=delete
Index at (const Key &r_localID) const
Convert a DoF's identifier in local space to the global one.
Index at (Index objectID, Index localIndex) const
Convert a DoF's identifier in local space to the global one.
template<concepts::Iterator< Index > TInputIT, concepts::Iterator< Index > TOutputIT>
void at (Index objectID, TInputIT it_inputBegin, const TInputIT it_inputEnd, TOutputIT it_outputBegin) const
Convert several DoFs' local identifiers of the same object at once.
template<concepts::Iterator< Index > TObjectIT>
void getObjectIDs (Index globalID, TObjectIT it_objectIDBegin) const
Get the indices of all objects that contain the specified DoF (identified by its ID in global space).
iterator insert (Key &&r_localID, Value globalID)
Insert a DoF's local-global identifier pair.
iterator insert (const Key &r_localID, Value globalID)
Insert a DoF's local-global identifier pair.
iterator insert (Index objectID, Index localIndex, Index globalID)
Insert a DoF's local-global identifier pair.
template<concepts::Iterator< Index > TLocalIT, concepts::Iterator< Index > TGlobalIndex>
iterator insert (Index objectID, TLocalIT it_localBegin, const TLocalIT it_localEnd, TGlobalIndex it_globalBegin)
Insert several DoF's local-global identifier pairs sharing an object.
Size size () const noexcept
Number of recorded DoFs.
const_iterator begin () const noexcept
iterator begin () noexcept
const_iterator end () const noexcept
iterator end () noexcept
Detailed Description
: globalID \f).
Todo:
Make accessing/inserting multiple DoFs within the same object more efficient.
Member Typedef Documentation
const_iterator
using cie::fem::AssemblyMap::const_iterator = Map::const_iterator
Index
using cie::fem::AssemblyMap::Index = Size
iterator
using cie::fem::AssemblyMap::iterator = Map::iterator
Key
using cie::fem::AssemblyMap::Key = StaticArray<Index,2>
value_type
using cie::fem::AssemblyMap::value_type = Map::value_type
Constructor & Destructor Documentation
AssemblyMap() [1/3]
cie::fem::AssemblyMap::AssemblyMap () default
AssemblyMap() [2/3]
cie::fem::AssemblyMap::AssemblyMap (AssemblyMap && r_rhs) default
AssemblyMap() [3/3]
cie::fem::AssemblyMap::AssemblyMap (const AssemblyMap & r_rhs) explicit default
Member Function Documentation
at() [1/3]
Index cie::fem::AssemblyMap::at (const Key & r_localID) const
Convert a DoF's identifier in local space to the global one.
Parameters
r_localID identifier of the DoF ibn local space consisting of an object ID and a local index.
at() [2/3]
Index cie::fem::AssemblyMap::at (Index objectID, Index localIndex) const
Convert a DoF's identifier in local space to the global one.
Parameters
objectID ID of the object the DoF belongs to.
localIndex DoF's local index within the object.
at() [3/3]
template<concepts::Iterator< Index > TInputIT, concepts::Iterator< Index > TOutputIT> void cie::fem::AssemblyMap::at (Index objectID, TInputIT it_inputBegin, const TInputIT it_inputEnd, TOutputIT it_outputBegin) const
Convert several DoFs' local identifiers of the same object at once.
Parameters
objectID ID of the object that owns all provided DoFs.
it_inputBegin iterator pointing to the first DoF's local index.
it_inputEnd iterator pointing past the last DoF's local index.
it_outputBegin output iterator specifying where the DoFs' global indices will be written to.
begin() [1/2]
const_iterator cie::fem::AssemblyMap::begin () const noexcept
begin() [2/2]
iterator cie::fem::AssemblyMap::begin () noexcept
end() [1/2]
const_iterator cie::fem::AssemblyMap::end () const noexcept
end() [2/2]
iterator cie::fem::AssemblyMap::end () noexcept
getObjectIDs()
template<concepts::Iterator< Index > TObjectIT> void cie::fem::AssemblyMap::getObjectIDs (Index globalID, TObjectIT it_objectIDBegin) const
Get the indices of all objects that contain the specified DoF (identified by its ID in global space).
Parameters
globalID the DoF's identifier in global space.
it_objectIDBegin output iterator pointing to a memory location where object IDs will be written.
insert() [1/4]
iterator cie::fem::AssemblyMap::insert (const Key & r_localID, Value globalID)
Insert a DoF's local-global identifier pair.
Parameters
r_localID Identifier of the DoF in local space consisting of an object ID and a local index.
globalID Identifier of the DoF in global space.
insert() [2/4]
iterator cie::fem::AssemblyMap::insert (Index objectID, Index localIndex, Index globalID)
Insert a DoF's local-global identifier pair.
Parameters
objectID ID of the object the DoF belongs to.
localIndex Index of the DoF withing its containing object.
globalID Identifier of the DoF in global space.
insert() [3/4]
template<concepts::Iterator< Index > TLocalIT, concepts::Iterator< Index > TGlobalIndex> iterator cie::fem::AssemblyMap::insert (Index objectID, TLocalIT it_localBegin, const TLocalIT it_localEnd, TGlobalIndex it_globalBegin)
Insert several DoF's local-global identifier pairs sharing an object.
Parameters
objectID ID of the object all provided DoFs belong to.
it_localBegin iterator pointing to the first DoF's index in local space.
it_localEnd iterator past the last DoF's index in local space.
it_globalBegin iterator pointing to the first DoF's identifier in global space.
insert() [4/4]
iterator cie::fem::AssemblyMap::insert (Key && r_localID, Value globalID)
Insert a DoF's local-global identifier pair.
Parameters
r_localID Identifier of the DoF in local space consisting of an object ID and a local index.
globalID Identifier of the DoF in global space.
operator=() [1/2]
AssemblyMap& cie::fem::AssemblyMap::operator= (AssemblyMap && r_rhs) default
operator=() [2/2]
AssemblyMap& cie::fem::AssemblyMap::operator= (const AssemblyMap & r_rhs) delete
size()
Size cie::fem::AssemblyMap::size () const noexcept
Number of recorded DoFs.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
The documentation for this class was generated from the following file:
AssemblyMap.hpp