fem: cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension > Class Template Reference
cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension > Class Template Reference
Fem
Expression representing the derivative of ProjectiveTransform.
Public Member Functions
ProjectiveTransformDerivative () noexcept
Identity by default.
void evaluate (ConstIterator it_begin, ConstIterator it_end, Iterator it_out) const
Evaluate the derivative at the provided point.
unsigned size () const noexcept
Get the number of scalar components returned by evaluate.
TValue evaluateDeterminant (ConstIterator it_begin, ConstIterator it_end) const
Compute the determinant of the projective transform's jacobian.
Friends
class ProjectiveTransform< TValue, Dimension >
Additional Inherited Members
Public Types inherited from cie::fem::maths::ExpressionTraits< TValue >
using Value = TValue
using Iterator = Ptr< TValue >
using ConstIterator = Ptr< const TValue >
Detailed Description
template<concepts::Numeric TValue, unsigned Dimension>
class cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension >
Expression representing the derivative of ProjectiveTransform.
Todo:
Implement in 3D (or any dimension).
The derivative is a \(D x D \) matrix that can be separated into an enumerator matrix, which is a matrix product of a 3D coefficient matrix and a 2D square matrix consisting of repeated copies of the homogeneous coordinates, and a scalar denominator, which is equal to the square of the inner product of the projective transform's last row and the homogeneous coordinates.
\[ \frac{\mathbf C \begin{bmatrix} \mathbf {\hat{x}} & \mathbf {\hat{x}} & \ldots & \mathbf {\hat{x}} \end{bmatrix}} {\begin{bmatrix} last\_row\_of\_ \mathbf T \end{bmatrix} \begin{bmatrix} x \\ y \\ \vdots \\ 1 \end{bmatrix}} \]
The 3D coefficient matrix is stored as a flattened matrix in the following index order 1) homogeneous component index (x, y, z, ..., w) 2) row index (Eigen stores column-major matrices by default) 3) column index
The 2D matrix of homogeneous coordinates takes the following form
\[ \begin{bmatrix} \mathbf {\hat{x}} & \mathbf {\hat{x}} & \ldots & \mathbf {\hat{x}} \end{bmatrix} = \begin{bmatrix} x & x & \ldots & x \\ y & y & \ldots & y \\ \vdots & \vdots & \ddots & \vdots \\ 1 & 1 & \ldots & 1 \end{bmatrix} \]
Constructor & Destructor Documentation
ProjectiveTransformDerivative()
template<concepts::Numeric TValue, unsigned Dimension> cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension >::ProjectiveTransformDerivative () noexcept
Identity by default.
Member Function Documentation
evaluate()
template<concepts::Numeric TValue, unsigned Dimension> void cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension >::evaluate (ConstIterator it_begin, ConstIterator it_end, Iterator it_out) const
Evaluate the derivative at the provided point.
Referenced by fem.discretization.basisfunctions.BasisFunctions::__call__(), and fem.discretization.basisfunctions.BasisFunctions::evaluateAll().
evaluateDeterminant()
template<concepts::Numeric TValue, unsigned Dimension> TValue cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension >::evaluateDeterminant (ConstIterator it_begin, ConstIterator it_end) const
Compute the determinant of the projective transform's jacobian.
size()
template<concepts::Numeric TValue, unsigned Dimension> unsigned cie::fem::maths::ProjectiveTransformDerivative< TValue, Dimension >::size () const noexcept
Get the number of scalar components returned by evaluate.
Referenced by fem.discretization.femodel.FEModel::allocateZeros(), fem.discretization.femodel.FEModel::applyDirichletBoundary(), fem.discretization.femodel.NonlinearFEModel::applyDirichletBoundary(), and fem.discretization.femodel.NonlinearTransientFEModel::applyDirichletBoundary().
Friends And Related Function Documentation
ProjectiveTransform< TValue, Dimension >
template<concepts::Numeric TValue, unsigned Dimension> friend class ProjectiveTransform< TValue, Dimension > friend
The documentation for this class was generated from the following file:
ProjectiveTransform.hpp