fem: cie::fem::Graph< TVertexData, TEdgeData > Class Template Reference
cie::fem::Graph< TVertexData, TEdgeData > Class Template Reference
A directed graph that automatically manages the connectivities of its vertices and edges.
Classes
class Edge
Edge type of Graph.
class Vertex
Vertex type of Graph.
Public Member Functions
CIE_STRONG_TYPEDEF (unsigned, VertexID)
CIE_STRONG_TYPEDEF (unsigned, EdgeID)
Graph () noexcept=default
Construct an empty Graph.
Ref< Vertex > insert (RightRef< Vertex > rVertex, bool overwrite=false)
Move a new Vertex into the Graph.
Ref< Vertex > insert (Ref< const Vertex > rVertex, bool overwrite=false)
Copy a new Vertex into the Graph.
Ref< Edge > insert (RightRef< Edge > rEdge, bool overwrite=false)
Move a new Edge into the Graph.
Ref< Edge > insert (Ref< const Edge > rEdge, bool overwrite=false)
Copy a new Edge into the Graph.
bool eraseVertex (VertexID id) noexcept
Erase the Vertex belonging to the provided ID, as well as every Edge connected to it.
bool eraseEdge (EdgeID id) noexcept
Erase the Edge belonging to the provided ID.
OptionalRef< const Vertex > findVertex (VertexID id) const noexcept
Find a Vertex in the Graph by its ID.
OptionalRef< Vertex > findVertex (VertexID id) noexcept
Find a Vertex in the Graph by its ID.
OptionalRef< const Vertex > find (VertexID id) const noexcept
Find a Vertex in the Graph by its ID.
OptionalRef< Vertex > find (VertexID id) noexcept
Find a Vertex in the Graph by its ID.
OptionalRef< const Edge > findEdge (EdgeID id) const noexcept
Find an Edge in the Graph by its ID.
OptionalRef< Edge > findEdge (EdgeID id) noexcept
Find an Edge in the Graph by its ID.
OptionalRef< const Edge > find (EdgeID id) const noexcept
Find an Edge in the Graph by its ID.
OptionalRef< Edge > find (EdgeID id) noexcept
Find an Edge in the Graph by its ID.
auto vertices () const noexcept
Immutable access to vertices in the Graph.
auto vertices () noexcept
Mutable access to vertices in the Graph.
auto edges () const noexcept
Immutable access to edges in the Graph.
auto edges () noexcept
Mutable access to edges in the Graph.
bool empty () const noexcept
Return true if the graph contains no vertices, false otherwise.
Detailed Description
template<class TVertexData, class TEdgeData>
class cie::fem::Graph< TVertexData, TEdgeData >
A directed graph that automatically manages the connectivities of its vertices and edges.
Template Parameters
TVertexData additional data type stored in each vertex.
TEdgeData additional data type stored in each edge.
Constructor & Destructor Documentation
Graph()
template<class TVertexData , class TEdgeData > cie::fem::Graph< TVertexData, TEdgeData >::Graph () default noexcept
Construct an empty Graph.
Member Function Documentation
CIE_STRONG_TYPEDEF() [1/2]
template<class TVertexData , class TEdgeData > cie::fem::Graph< TVertexData, TEdgeData >::CIE_STRONG_TYPEDEF (unsigned , EdgeID)
CIE_STRONG_TYPEDEF() [2/2]
template<class TVertexData , class TEdgeData > cie::fem::Graph< TVertexData, TEdgeData >::CIE_STRONG_TYPEDEF (unsigned , VertexID)
edges() [1/2]
template<class TVertexData , class TEdgeData > auto cie::fem::Graph< TVertexData, TEdgeData >::edges () const inline noexcept
Immutable access to edges in the Graph.
Returns
an immutable view over all edges.
References cie::utils::makeNoOpIterator().
edges() [2/2]
template<class TVertexData , class TEdgeData > auto cie::fem::Graph< TVertexData, TEdgeData >::edges () inline noexcept
Mutable access to edges in the Graph.
Returns
a mutable view over all vertices.
References cie::utils::makeNoOpIterator().
empty()
template<class TVertexData , class TEdgeData > bool cie::fem::Graph< TVertexData, TEdgeData >::empty () const noexcept
Return true if the graph contains no vertices, false otherwise.
eraseEdge()
template<class TVertexData , class TEdgeData > bool cie::fem::Graph< TVertexData, TEdgeData >::eraseEdge (EdgeID id) noexcept
Erase the Edge belonging to the provided ID.
Parameters
id ID of the edge to erase.
Also erases the edge ID from the edge set of every connected Vertex. Does nothing if no edge exists with the provided id.
Returns
true if an edge was erased, otherwise false.
eraseVertex()
template<class TVertexData , class TEdgeData > bool cie::fem::Graph< TVertexData, TEdgeData >::eraseVertex (VertexID id) noexcept
Erase the Vertex belonging to the provided ID, as well as every Edge connected to it.
Parameters
id ID of the vertex to erase.
Does nothing if no vertex exists in the Graph with the provided id.
See also
eraseEdge
Returns
true if a vertex was erased, otherwise false.
find() [1/4]
template<class TVertexData , class TEdgeData > OptionalRef<const Edge> cie::fem::Graph< TVertexData, TEdgeData >::find (EdgeID id) const noexcept
Find an Edge in the Graph by its ID.
Parameters
id identifier of the edge to find.
Returns
an immutable reference to the edge with the matching id, or an empty OptionalRef if no such edge exists in the graph.
find() [2/4]
template<class TVertexData , class TEdgeData > OptionalRef<Edge> cie::fem::Graph< TVertexData, TEdgeData >::find (EdgeID id) noexcept
Find an Edge in the Graph by its ID.
Parameters
id identifier of the edge to find.
Returns
a mutable reference to the edge with the matching id, or an empty OptionalRef if no such edge exists in the graph.
find() [3/4]
template<class TVertexData , class TEdgeData > OptionalRef<const Vertex> cie::fem::Graph< TVertexData, TEdgeData >::find (VertexID id) const noexcept
Find a Vertex in the Graph by its ID.
Parameters
id identifier of the vertex to find.
Returns
an immutable reference to the vertex with the matching id, or an empty OptionalRef if no such vertex exists in the graph.
find() [4/4]
template<class TVertexData , class TEdgeData > OptionalRef<Vertex> cie::fem::Graph< TVertexData, TEdgeData >::find (VertexID id) noexcept
Find a Vertex in the Graph by its ID.
Parameters
id identifier of the vertex to find.
Returns
a mutable reference to the vertex with the matching id, or an empty OptionalRef if no such vertex exists in the graph.
findEdge() [1/2]
template<class TVertexData , class TEdgeData > OptionalRef<const Edge> cie::fem::Graph< TVertexData, TEdgeData >::findEdge (EdgeID id) const noexcept
Find an Edge in the Graph by its ID.
Parameters
id identifier of the edge to find.
Returns
an immutable reference to the edge with the matching id, or an empty OptionalRef if no such edge exists in the graph.
findEdge() [2/2]
template<class TVertexData , class TEdgeData > OptionalRef<Edge> cie::fem::Graph< TVertexData, TEdgeData >::findEdge (EdgeID id) noexcept
Find an Edge in the Graph by its ID.
Parameters
id identifier of the edge to find.
Returns
a mutable reference to the edge with the matching id, or an empty OptionalRef if no such edge exists in the graph.
findVertex() [1/2]
template<class TVertexData , class TEdgeData > OptionalRef<const Vertex> cie::fem::Graph< TVertexData, TEdgeData >::findVertex (VertexID id) const noexcept
Find a Vertex in the Graph by its ID.
Parameters
id identifier of the vertex to find.
Returns
an immutable reference to the vertex with the matching id, or an empty OptionalRef if no such vertex exists in the graph.
findVertex() [2/2]
template<class TVertexData , class TEdgeData > OptionalRef<Vertex> cie::fem::Graph< TVertexData, TEdgeData >::findVertex (VertexID id) noexcept
Find a Vertex in the Graph by its ID.
Parameters
id identifier of the vertex to find.
Returns
a mutable reference to the vertex with the matching id, or an empty OptionalRef if no such vertex exists in the graph.
insert() [1/4]
template<class TVertexData , class TEdgeData > Ref<Edge> cie::fem::Graph< TVertexData, TEdgeData >::insert (Ref< const Edge > rEdge, bool overwrite = false)
Copy a new Edge into the Graph.
Parameters
rEdge new edge to be copied into the graph.
overwrite in case of ID clashes, this argument controls whether to replace the existing edge with the provided one, or do nothing.
If an edge with an identical ID already exists in the graph, two things can happen depending on the value of overwrite. If overwrite is false (default), then the existing edge remains in the graph and the new one is discarded. If overwrite is true, first the existing edge is erased (eraseEdge), then the new one is inserted.
If the newly inserted edge connects vertices that are not yet part of the graph, default constructed ones are inserted.
See also
eraseEdge
insert() [2/4]
template<class TVertexData , class TEdgeData > Ref<Vertex> cie::fem::Graph< TVertexData, TEdgeData >::insert (Ref< const Vertex > rVertex, bool overwrite = false)
Copy a new Vertex into the Graph.
Parameters
rVertex new vertex to be copied into the graph.
overwrite in case of ID clashes, this argument controls whether to replace the existing vertex with the provided one, or do nothing.
If a vertex with an identical ID already exists in the graph, two things can happen depending on the value of overwrite. If overwrite is false (default), then the existing vertex remains in the graph and the new one is discarded. If overwrite is true, first the existing vertex is erased (eraseVertex), then the new one is inserted.
See also
eraseVertex
Returns
A mutable reference to the newly inserted, or existing vertex.
Note
The new vertex' Edge set must be empty. It will be filled automatically by the graph upon edge insertion.
Exceptions
If the edge set of the new vertex is not empty.
insert() [3/4]
template<class TVertexData , class TEdgeData > Ref<Edge> cie::fem::Graph< TVertexData, TEdgeData >::insert (RightRef< Edge > rEdge, bool overwrite = false)
Move a new Edge into the Graph.
Parameters
rEdge new edge to be moved into the graph.
overwrite in case of ID clashes, this argument controls whether to replace the existing edge with the provided one, or do nothing.
If an edge with an identical ID already exists in the graph, two things can happen depending on the value of overwrite. If overwrite is false (default), then the existing edge remains in the graph and the new one is discarded. If overwrite is true, first the existing edge is erased (eraseEdge), then the new one is inserted.
If the newly inserted edge connects vertices that are not yet part of the graph, default constructed ones are inserted.
See also
eraseEdge
insert() [4/4]
template<class TVertexData , class TEdgeData > Ref<Vertex> cie::fem::Graph< TVertexData, TEdgeData >::insert (RightRef< Vertex > rVertex, bool overwrite = false)
Move a new Vertex into the Graph.
Parameters
rVertex new vertex to be moved into the graph.
overwrite in case of ID clashes, this argument controls whether to replace the existing vertex with the provided one, or do nothing.
If a vertex with an identical ID already exists in the graph, two things can happen depending on the value of overwrite. If overwrite is false (default), then the existing vertex remains in the graph and the new one is discarded. If overwrite is true, first the existing vertex is erased (eraseVertex), then the new one is inserted.
See also
eraseVertex
Returns
A mutable reference to the newly inserted, or existing vertex.
Note
The new vertex' Edge set must be empty. It will be filled automatically by the graph upon edge insertion.
Exceptions
If the edge set of the new vertex is not empty.
vertices() [1/2]
template<class TVertexData , class TEdgeData > auto cie::fem::Graph< TVertexData, TEdgeData >::vertices () const inline noexcept
Immutable access to vertices in the Graph.
Returns
an immutable view over all vertices.
References cie::utils::makeNoOpIterator().
vertices() [2/2]
template<class TVertexData , class TEdgeData > auto cie::fem::Graph< TVertexData, TEdgeData >::vertices () inline noexcept
Mutable access to vertices in the Graph.
Returns
a mutable view over all vertices.
References cie::utils::makeNoOpIterator().
The documentation for this class was generated from the following file:
Graph.hpp