fem: fem.numeric.finitedifferences Namespace Reference
fem.numeric.finitedifferences Namespace Reference
Functions
def solveLinearHeat1D (time, initialSolution, model, theta=0.5)
Arguments: time : discretized time domain initialSolution : solution at t=0 model : TransientFEModel with mass, stiffness, load, and loadFunction theta=0.5 : implicitness.
def solveAdjointLinearHeat1D (time, adjointRHS, model, theta=0.5, initialAdjointSolution=None)
Arguments: time : discretized time domain adjointRHS : FESolution - referenceFESolution model : TransientFEModel with mass, stiffness theta=0.5 : implicitness initialAdjointSolution=None : zeros by default.
def solveNonlinearHeat1D (time, initialSolution, model, theta=0.5, nonlinearSolver=transientFixedPointIteration, **kwargs)
Arguments: time : discretized time domain initialSolution : solution at t=0 model : NonlinearTransientFEModel with at least mass, stiffness, load, and loadFunction theta : implicitness nonlinearSolver : either a variant of the Newton method or a fixed point iteration kwargs : keyword arguments of the nonlinearSolver.
def solveAdjointNonlinearHeat1D (model, theta=0.5, initialAdjointSolution=None)
Function Documentation
solveAdjointLinearHeat1D()
def fem.numeric.finitedifferences.solveAdjointLinearHeat1D (time, adjointRHS, model, theta = 0.5, initialAdjointSolution = None)
Arguments: time : discretized time domain adjointRHS : FESolution - referenceFESolution model : TransientFEModel with mass, stiffness theta=0.5 : implicitness initialAdjointSolution=None : zeros by default.
References fem.numeric.solver.solveLinearSystem().
solveAdjointNonlinearHeat1D()
def fem.numeric.finitedifferences.solveAdjointNonlinearHeat1D (model, theta = 0.5, initialAdjointSolution = None)
References fem.numeric.solver.solveLinearSystem().
solveLinearHeat1D()
def fem.numeric.finitedifferences.solveLinearHeat1D (time, initialSolution, model, theta = 0.5)
Arguments: time : discretized time domain initialSolution : solution at t=0 model : TransientFEModel with mass, stiffness, load, and loadFunction theta=0.5 : implicitness.
References fem.numeric.solver.solveLinearSystem().
solveNonlinearHeat1D()
def fem.numeric.finitedifferences.solveNonlinearHeat1D (time, initialSolution, model, theta = 0.5, nonlinearSolver = transientFixedPointIteration, ** kwargs)
Arguments: time : discretized time domain initialSolution : solution at t=0 model : NonlinearTransientFEModel with at least mass, stiffness, load, and loadFunction theta : implicitness nonlinearSolver : either a variant of the Newton method or a fixed point iteration kwargs : keyword arguments of the nonlinearSolver.