fem: fem.numeric.nonlinearsolver Namespace Reference
fem.numeric.nonlinearsolver Namespace Reference
Functions
def newtonIteration (targetSystem, initialSolution, tolerance=1e-5, maxIterations=10, solverKWArgs={}, verbose=False, convergencePlot=None)
Attempts to find a root of a target function, using 1st order linearization.
def reintegrate (model, loadFactor, solution, stiffness=True, load=True, mass=True, geometricStiffness=True)
Function that does all the necessary operations for updating the model to the current load factor and solution.
def stationaryLoadControl (model, initialSolution, baseIncrement=0.5, minIncrement=0.05, maxIncrement=1.0, maxIncrements=50, maxCorrections=10, tolerance=1e-5, verbose=True, axes=None, convergencePlot=None)
Solves a nonlinear FEModel using a load controlled predictor and a constant load corrector.
def stationaryFixedPointIteration (model, initialSolution, loadFactors=None, maxCorrections=10, tolerance=1e-5, verbose=True, axes=None, convergencePlot=None)
Solves a nonlinear FEModel using fixed point iterations.
def transientResidual (model, solution, loadFactor, massInverse, theta, dt, previousState)
def transientResidualDerivative (model, solution, loadFactor, massInverse, theta, dt)
Compute the derivative of the residual with respect to the solution coefficients.
def transientLoadControl (model, initialSolution, initialStiffness, initialMass, initialLoad, dt, baseIncrement=0.5, minIncrement=0.05, maxIncrement=1.0, maxIncrements=50, maxCorrections=10, tolerance=1e-5, theta=0.5, verbose=True, axes=None, convergencePlot=None)
Solves a nonlinear transient FEModel using a load controlled predictor and a constant load corrector.
def transientFixedPointIteration (model, initialSolution, initialStiffness, initialMass, initialLoad, dt, loadFactors=None, maxCorrections=10, tolerance=1e-5, theta=0.5, verbose=True, convergencePlot=None)
Solves a transient nonlinear FEModel using fixed point iterations (Arguments are copied internally)
Function Documentation
newtonIteration()
def fem.numeric.nonlinearsolver.newtonIteration (targetSystem, initialSolution, tolerance = 1e-5, maxIterations = 10, solverKWArgs = {}, verbose = False, convergencePlot = None)
Attempts to find a root of a target function, using 1st order linearization.
The target function must return a 1D numpy array, while the target derivative must return a matching nonsingular square numpy ndarray. Both the function and derivative must expect the initial state (1D numpy array) as argument (and no other positional arguments).
References fem.numeric.solver.solveLinearSystem().
Referenced by fem.numeric.nonlinearsolver.stationaryLoadControl(), and fem.numeric.nonlinearsolver.transientLoadControl().
reintegrate()
def fem.numeric.nonlinearsolver.reintegrate (model, loadFactor, solution, stiffness = True, load = True, mass = True, geometricStiffness = True)
Function that does all the necessary operations for updating the model to the current load factor and solution.
Referenced by fem.numeric.nonlinearsolver.stationaryFixedPointIteration(), fem.numeric.nonlinearsolver.stationaryLoadControl(), fem.numeric.nonlinearsolver.transientFixedPointIteration(), and fem.numeric.nonlinearsolver.transientLoadControl().
stationaryFixedPointIteration()
def fem.numeric.nonlinearsolver.stationaryFixedPointIteration (model, initialSolution, loadFactors = None, maxCorrections = 10, tolerance = 1e-5, verbose = True, axes = None, convergencePlot = None)
Solves a nonlinear FEModel using fixed point iterations.
References fem.numeric.nonlinearsolver.reintegrate(), and fem.numeric.solver.solveLinearSystem().
stationaryLoadControl()
def fem.numeric.nonlinearsolver.stationaryLoadControl (model, initialSolution, baseIncrement = 0.5, minIncrement = 0.05, maxIncrement = 1.0, maxIncrements = 50, maxCorrections = 10, tolerance = 1e-5, verbose = True, axes = None, convergencePlot = None)
Solves a nonlinear FEModel using a load controlled predictor and a constant load corrector.
References fem.numeric.nonlinearsolver.newtonIteration(), fem.numeric.nonlinearsolver.reintegrate(), and fem.numeric.solver.solveLinearSystem().
transientFixedPointIteration()
def fem.numeric.nonlinearsolver.transientFixedPointIteration (model, initialSolution, initialStiffness, initialMass, initialLoad, dt, loadFactors = None, maxCorrections = 10, tolerance = 1e-5, theta = 0.5, verbose = True, convergencePlot = None)
Solves a transient nonlinear FEModel using fixed point iterations (Arguments are copied internally)
References fem.numeric.nonlinearsolver.reintegrate(), and fem.numeric.solver.solveLinearSystem().
transientLoadControl()
def fem.numeric.nonlinearsolver.transientLoadControl (model, initialSolution, initialStiffness, initialMass, initialLoad, dt, baseIncrement = 0.5, minIncrement = 0.05, maxIncrement = 1.0, maxIncrements = 50, maxCorrections = 10, tolerance = 1e-5, theta = 0.5, verbose = True, axes = None, convergencePlot = None)
Solves a nonlinear transient FEModel using a load controlled predictor and a constant load corrector.
References fem.numeric.nonlinearsolver.newtonIteration(), fem.numeric.nonlinearsolver.reintegrate(), fem.numeric.solver.solveLinearSystem(), fem.numeric.nonlinearsolver.transientResidual(), and fem.numeric.nonlinearsolver.transientResidualDerivative().
transientResidual()
def fem.numeric.nonlinearsolver.transientResidual (model, solution, loadFactor, massInverse, theta, dt, previousState)
Referenced by fem.numeric.nonlinearsolver.transientLoadControl().
transientResidualDerivative()
def fem.numeric.nonlinearsolver.transientResidualDerivative (model, solution, loadFactor, massInverse, theta, dt)
Compute the derivative of the residual with respect to the solution coefficients.
See the readme for a better view: eq.(23)
Referenced by fem.numeric.nonlinearsolver.transientLoadControl().