fem: fem.numeric.solver Namespace Reference
fem.numeric.solver Namespace Reference
Functions
def solveLinearSystem (A, b, *args, x0=None, sparse=True, **kwargs)
Wrapper function to simplify changing linear solvers in the future.
Function Documentation
solveLinearSystem()
def fem.numeric.solver.solveLinearSystem (A, b, * args, x0 = None, sparse = True, ** kwargs)
Wrapper function to simplify changing linear solvers in the future.
Referenced by fem.numeric.nonlinearsolver.newtonIteration(), fem.numeric.finitedifferences.solveAdjointLinearHeat1D(), fem.numeric.finitedifferences.solveAdjointNonlinearHeat1D(), fem.numeric.finitedifferences.solveLinearHeat1D(), fem.numeric.nonlinearsolver.stationaryFixedPointIteration(), fem.numeric.nonlinearsolver.stationaryLoadControl(), fem.numeric.nonlinearsolver.transientFixedPointIteration(), and fem.numeric.nonlinearsolver.transientLoadControl().