fem: optcontrol.adjoint_optimization Namespace Reference
optcontrol.adjoint_optimization Namespace Reference
Functions
def call (x)
Variables
int nTime = 80
float dt = 1.0/nTime
float theta = 0.5
float pausetime = 0.005
float k = 1.0
float c = 1.0
float stationaryDistributedSource = lambda x: 0.0
float transientDistributedSource = lambda t, x: 0.0
float leftNeumannBoundaryFlux = lambda t: 1.0
float rightNeumannBoundaryFlux = lambda t: 0.0
float leftDirichletValue = 0.0
float rightDirichletValue = 0.0
string leftBC = "neumann"
string rightBC = "dirichlet"
float length = 1.0
int p = 3
int n = 50
float h = length/n
int integrationOrder = p + 5
int nDofs = p * n + 1
gaussPoints = integration.getGaussLegendreIntegrationPoints(integrationOrder)
basisFunctions = basisfunctions.IntegratedLegendre()
float l = 1.0e-2
int maxOptIter = 15
float lowBound = 0.0
float upBound = 0.04
float functionalValue = 0.0
float leftDirichletBoundaryValue = 0.0
float rightDirichletBoundaryValue = 0.0
int penaltyValue = 1e8;
int numberOfResultPointsPerElement = 3 + p * 2
list axisBounds = [0, 1, -1, 1]
list labels = ["forw. sol.", "ref. sol.", "dual sol."]
int plotTime = 1
locationMaps = np.zeros((n, p+1)).astype(int);
locationMap = np.array([iElement, iElement + 1])
K
M
F
referenceSols = np.zeros(nDofs*nTime)
forwardSols = np.zeros(nDofs*nTime)
approxRHS = np.zeros(nDofs*nTime)
backwardSols = np.zeros(nDofs*nTime)
backwardRHS = np.zeros(nDofs*nTime)
referenceRHS = integrate.integrateTransientRHS(n, p, length, transientDistributedSource, basisFunctions, locationMaps, gaussPoints, nTime)
int idLeft = 0
int idRight = n
tuple forwLeftMatrix = (1./dt)*M + theta*K
tuple forwRightMatrix = (1./dt)*M - (1. - theta)*K
tuple backwLeftMatrix = (1./dt)*M + theta*K
tuple backwRightMatrix = (1./dt)*M - (1.-theta)*K
refY = np.zeros(nDofs)
approxY = np.zeros(nDofs)
int t = 0
float rhscn = np.dot(forwRightMatrix, refY) + theta*referenceRHS[nDofs*t:nDofs*(t+1)] + (1-theta)*referenceRHS[nDofs*(t-1):nDofs*t]
list measurements = []
optRHS = so.fmin_l_bfgs_b(call, np.zeros(nTime), fprime=None, approx_grad=False, bounds=[(0, 1) for i in range(nTime)], maxiter=10, maxfun=40, disp=1, pgtol=1e-20, factr=1e0)
finDiffRHS = np.sum((referenceRHS - approxRHS)**2)
float finDiffT = 0.5*dt*integrate.integrateSquaredL2Norm(n, p, length, basisFunctions, locationMaps, gaussPoints, (forwardSols-referenceSols), nTime)
Function Documentation
call()
def optcontrol.adjoint_optimization.call (x)
Variable Documentation
approxRHS
optcontrol.adjoint_optimization.approxRHS = np.zeros(nDofs*nTime)
approxY
optcontrol.adjoint_optimization.approxY = np.zeros(nDofs)
axisBounds
list optcontrol.adjoint_optimization.axisBounds = [0, 1, -1, 1]
backwardRHS
optcontrol.adjoint_optimization.backwardRHS = np.zeros(nDofs*nTime)
backwardSols
optcontrol.adjoint_optimization.backwardSols = np.zeros(nDofs*nTime)
backwLeftMatrix
tuple optcontrol.adjoint_optimization.backwLeftMatrix = (1./dt)*M + theta*K
backwRightMatrix
tuple optcontrol.adjoint_optimization.backwRightMatrix = (1./dt)*M - (1.-theta)*K
basisFunctions
optcontrol.adjoint_optimization.basisFunctions = basisfunctions.IntegratedLegendre()
Referenced by optcontrol.integrate.integrateSqL2stat(), optcontrol.integrate.integrateSquaredL2Norm(), optcontrol.integrate.integrateStiffnessMassRHS(), optcontrol.integrate.integrateTransientRHS(), and optcontrol.plotter.plotter.plot().
c
float optcontrol.adjoint_optimization.c = 1.0
dt
float optcontrol.adjoint_optimization.dt = 1.0/nTime
F
optcontrol.adjoint_optimization.F
finDiffRHS
optcontrol.adjoint_optimization.finDiffRHS = np.sum((referenceRHS - approxRHS)**2)
finDiffT
float optcontrol.adjoint_optimization.finDiffT = 0.5*dt*integrate.integrateSquaredL2Norm(n, p, length, basisFunctions, locationMaps, gaussPoints, (forwardSols-referenceSols), nTime)
forwardSols
optcontrol.adjoint_optimization.forwardSols = np.zeros(nDofs*nTime)
forwLeftMatrix
tuple optcontrol.adjoint_optimization.forwLeftMatrix = (1./dt)*M + theta*K
forwRightMatrix
tuple optcontrol.adjoint_optimization.forwRightMatrix = (1./dt)*M - (1. - theta)*K
functionalValue
float optcontrol.adjoint_optimization.functionalValue = 0.0
gaussPoints
optcontrol.adjoint_optimization.gaussPoints = integration.getGaussLegendreIntegrationPoints(integrationOrder)
h
float optcontrol.adjoint_optimization.h = length/n
idLeft
int optcontrol.adjoint_optimization.idLeft = 0
idRight
int optcontrol.adjoint_optimization.idRight = n
integrationOrder
int optcontrol.adjoint_optimization.integrationOrder = p + 5
k
float optcontrol.adjoint_optimization.k = 1.0
K
optcontrol.adjoint_optimization.K
l
int optcontrol.adjoint_optimization.l = 1.0e-2
labels
list optcontrol.adjoint_optimization.labels = ["forw. sol.", "ref. sol.", "dual sol."]
leftBC
string optcontrol.adjoint_optimization.leftBC = "neumann"
leftDirichletBoundaryValue
float optcontrol.adjoint_optimization.leftDirichletBoundaryValue = 0.0
leftDirichletValue
float optcontrol.adjoint_optimization.leftDirichletValue = 0.0
leftNeumannBoundaryFlux
float optcontrol.adjoint_optimization.leftNeumannBoundaryFlux = lambda t: 1.0
length
float optcontrol.adjoint_optimization.length = 1.0
locationMap
optcontrol.adjoint_optimization.locationMap = np.array([iElement, iElement + 1])
locationMaps
optcontrol.adjoint_optimization.locationMaps = np.zeros((n, p+1)).astype(int);
lowBound
float optcontrol.adjoint_optimization.lowBound = 0.0
M
optcontrol.adjoint_optimization.M
maxOptIter
int optcontrol.adjoint_optimization.maxOptIter = 15
measurements
list optcontrol.adjoint_optimization.measurements = []
n
int optcontrol.adjoint_optimization.n = 50
nDofs
int optcontrol.adjoint_optimization.nDofs = p * n + 1
nTime
int optcontrol.adjoint_optimization.nTime = 80
numberOfResultPointsPerElement
int optcontrol.adjoint_optimization.numberOfResultPointsPerElement = 3 + p * 2
optRHS
optcontrol.adjoint_optimization.optRHS = so.fmin_l_bfgs_b(call, np.zeros(nTime), fprime=None, approx_grad=False, bounds=[(0, 1) for i in range(nTime)], maxiter=10, maxfun=40, disp=1, pgtol=1e-20, factr=1e0)
p
int optcontrol.adjoint_optimization.p = 3
pausetime
float optcontrol.adjoint_optimization.pausetime = 0.005
penaltyValue
int optcontrol.adjoint_optimization.penaltyValue = 1e8;
plotTime
int optcontrol.adjoint_optimization.plotTime = 1
referenceRHS
optcontrol.adjoint_optimization.referenceRHS = integrate.integrateTransientRHS(n, p, length, transientDistributedSource, basisFunctions, locationMaps, gaussPoints, nTime)
referenceSols
optcontrol.adjoint_optimization.referenceSols = np.zeros(nDofs*nTime)
refY
optcontrol.adjoint_optimization.refY = np.zeros(nDofs)
rhscn
float optcontrol.adjoint_optimization.rhscn = np.dot(forwRightMatrix, refY) + theta*referenceRHS[nDofs*t:nDofs*(t+1)] + (1-theta)*referenceRHS[nDofs*(t-1):nDofs*t]
rightBC
string optcontrol.adjoint_optimization.rightBC = "dirichlet"
rightDirichletBoundaryValue
float optcontrol.adjoint_optimization.rightDirichletBoundaryValue = 0.0
rightDirichletValue
float optcontrol.adjoint_optimization.rightDirichletValue = 0.0
rightNeumannBoundaryFlux
float optcontrol.adjoint_optimization.rightNeumannBoundaryFlux = lambda t: 0.0
stationaryDistributedSource
float optcontrol.adjoint_optimization.stationaryDistributedSource = lambda x: 0.0
t
int optcontrol.adjoint_optimization.t = 0
theta
float optcontrol.adjoint_optimization.theta = 0.5
transientDistributedSource
float optcontrol.adjoint_optimization.transientDistributedSource = lambda t, x: 0.0
upBound
float optcontrol.adjoint_optimization.upBound = 0.04