fem: fem.utilities.typecheck Namespace Reference
fem.utilities.typecheck Namespace Reference
Functions
def isArray (var)
def isNumpyArray (var)
Function Documentation
isArray()
def fem.utilities.typecheck.isArray (var)
Referenced by fem.discretization.basisfunctions.BasisFunctions.evaluateAll(), fem.discretization.element.Element1D.toGlobalCoordinates(), and fem.discretization.element.Element1D.toLocalCoordinates().
isNumpyArray()
def fem.utilities.typecheck.isNumpyArray (var)
Referenced by fem.discretization.element.Element1D.__call__(), fem.discretization.element.Element1D.derivative(), and fem.discretization.basisfunctions.BasisFunctions.evaluate().